import { ReminderProvider } from './context/store'
import './globals.css'
import { Inter } from 'next/font/google'
// import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Twilio Reminder App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReminderProvider>
          {children}
        </ReminderProvider>
      </body>
    </html>
  )
}
